services:
  frontend:
    image: gregorynt/wine_llmops-frontend:latest
    # build: streamlit_frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./streamlit_frontend:/app
    restart: always
    networks:
      - app
    container_name: streamlit_frontend

  backend:
    image: gregorynt/wine_llmops-backend:latest
    build: fastapi_backend
    ports:
      - 8000:8000
    volumes:
      - ./fastapi_backend:/app
    restart: always
    env_file:
      - .env
    networks:
      - app
    container_name: backenfastapi_backend

networks:
  app:
    driver: bridge