# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy app to Azure Web App - barneyllm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://winellmops.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_32040161a0c044979997b69bbf8732ac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3246ec155a8446508e678ae2850e8556 }}

    # Build and push backend image to registry
    - name: Build and push backend container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./fastapi_backend
        push: true
        tags: winellmops.azurecr.io/wine_llmops-backend:${{ github.sha }}
        
    # Build and push frontend image to registry
    - name: Build and push frontend container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./streamlit_frontend
        push: true
        tags: winellmops.azurecr.io/wine_llmops-frontend:${{ github.sha }}
   
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'barneyllm'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bddc38c58bfa48cdad98df445e697d67 }}
        multi-container-config-file: ./docker-compose-az.yml
